### ISSUE TITLE
Format research.

### ISSUE THREAD

**Issue by nikosgram13** [renegens/AndroidLover.org#1]
Ψάξε λίγο περισσότερο για το πως μπορείς να κάνεις τον κώδικα πιο ωραίο και κατανοητό. :smile:

**Comment by renegens** [comment]
//When I wrote this, only God and I understood what I was doing
//Now, God only knows

**Comment by nikosgram13** [comment]
Χαχαχαχαχαχα, το πιστεύω :dancers:
